[package]
name = "rust-6502"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rstest = "0.18.2"